version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/web/:/usr/share/nginx/html/
  rstudio:
    container_name: rstudio
    build: ./users
    environment: 
      PASSWORD: password
  shiny:
    container_name: shiny
    image: rocker/shiny
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./apps:/srv/shiny-server

